name: nacho_chat
description: A frontend for the chat-api

publish_to: "none"

version: 1.5.99+357

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  provider: 6.1.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.1.5
  jwt_decode: 0.3.1
  json_annotation: 4.9.0
  openapi:
    path: ./api
  cached_network_image: 3.4.1
  socket_io_client: 3.1.2
  logger: 2.5.0
  built_value: 8.10.1
  built_collection: 5.1.1
  flutter_localization: 0.3.2
  intl: 0.20.2
  file_picker: 10.2.0
  package_info_plus: 8.3.0
  flutter_blurhash: 0.9.1
  time_machine: 0.9.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  lint: 2.8.0
  build_runner: 2.5.3
  json_serializable: 6.9.5
  version_bmp: 1.2.3

flutter:
  generate: true
  uses-material-design: true